In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r'D:/youtube_ai/final_dataset.csv')

In [3]:
df.head()

x0   x1   x2   x3   x4   x5   x6   x7   x8   x9  ...  y12  y13  y14  y15  \
0  265  392  273  335  307  283  335  239  341  204  ...  382  413  381  433   
1  261  395  271  337  307  286  334  242  341  207  ...  381  409  386  427   
2  266  393  274  336  307  285  335  242  342  208  ...  381  412  384  430   
3  268  391  277  335  310  285  337  242  343  208  ...  379  416  384  432   
4  270  391  278  335  312  284  339  242  345  207  ...  379  418  382  435   

   y16  y17  y18  y19  y20  label  
0  403  409  411  388  407      0  
1  405  404  411  383  407      0  
2  403  407  410  385  406      0  
3  403  409  409  388  405      0  
4  404  411  410  389  406      0  

[5 rows x 43 columns]

In [4]:
df.tail()

x0   x1   x2   x3   x4   x5   x6   x7   x8   x9  ...  y12  y13  y14  \
2535  305  366  330  349  346  317  332  296  309  299  ...  310  281  305   
2536  305  366  329  349  345  317  332  295  309  298  ...  310  281  305   
2537  305  368  330  351  345  319  332  298  309  301  ...  311  280  307   
2538  305  368  330  351  345  318  332  297  309  300  ...  312  281  307   
2539  305  368  330  351  346  318  332  295  310  298  ...  313  281  306   

      y15  y16  y17  y18  y19  y20  label  
2535  282  290  287  307  287  313      4  
2536  283  291  288  307  287  313      4  
2537  282  292  287  309  287  314      4  
2538  283  292  288  309  287  315      4  
2539  282  292  288  309  288  315      4  

[5 rows x 43 columns]

In [5]:
X = df.drop('label', axis=1).values  # shape: (num_samples, 42)
y = df['label'].values

In [6]:
y


array([0, 0, 0, ..., 4, 4, 4], dtype=int64)

In [7]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)


In [8]:
X


array([[0.3198324 , 0.8364486 , 0.35059172, ..., 0.86111111, 0.55500821,
        0.84195402],
       [0.31424581, 0.84345794, 0.34763314, ..., 0.86111111, 0.54679803,
        0.84195402],
       [0.32122905, 0.83878505, 0.35207101, ..., 0.85833333, 0.5500821 ,
        0.83908046],
       ...,
       [0.37569832, 0.78037383, 0.43491124, ..., 0.57777778, 0.38916256,
        0.57471264],
       [0.37569832, 0.78037383, 0.43491124, ..., 0.57777778, 0.38916256,
        0.57758621],
       [0.37569832, 0.78037383, 0.43491124, ..., 0.57777778, 0.3908046 ,
        0.57758621]])

In [9]:
# Encode labels
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [10]:
y_encoded

array([0, 0, 0, ..., 4, 4, 4], dtype=int64)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

In [12]:
model = Sequential([
    Dense(128, activation='relu', input_shape=(42,)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(9, activation='softmax')  
])

c:\Users\javaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [14]:
model.fit(X_train, y_train, epochs=30, validation_data=(X_test, y_test), batch_size=32)

Epoch 1/30
64/64 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.2629 - loss: 1.8635 - val_accuracy: 0.8583 - val_loss: 1.1153
Epoch 2/30
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6489 - loss: 1.0565 - val_accuracy: 1.0000 - val_loss: 0.3860
Epoch 3/30
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9356 - loss: 0.4185 - val_accuracy: 1.0000 - val_loss: 0.1130
Epoch 4/30
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9904 - loss: 0.1650 - val_accuracy: 1.0000 - val_loss: 0.0418
Epoch 5/30
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9971 - loss: 0.0746 - val_accuracy: 1.0000 - val_loss: 0.0199
Epoch 6/30
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9991 - loss: 0.0438 - val_accuracy: 1.0000 - val_loss: 0.0113
Epoch 7/30
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9967 - loss: 0.0358 - val_accuracy: 1.0000 - val_loss: 0.0069
Epoch 8/30
64/64 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9998 - loss: 0.0233 - val_accuracy: 1.0000 - val_loss:

In [15]:
prediction_lastlayer=model.predict(X_test)

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [16]:
prediction_lastlayer

array([[2.7098064e-04, 3.9554543e-05, 5.5960534e-08, ..., 1.1271983e-06,
        6.4958869e-07, 2.2636248e-06],
       [9.9999845e-01, 2.3881256e-07, 6.9277606e-10, ..., 2.3808420e-09,
        5.3152444e-10, 1.3575854e-09],
       [8.7614921e-05, 2.2268598e-05, 4.8601243e-09, ..., 1.5150147e-07,
        9.1885731e-08, 3.6976274e-07],
       ...,
       [9.9999487e-01, 1.7843587e-06, 3.2442678e-08, ..., 2.9054819e-08,
        9.9350430e-09, 2.0771832e-08],
       [6.4068541e-07, 4.2924999e-06, 9.9999380e-01, ..., 5.3913931e-09,
        1.3305219e-08, 1.7843609e-09],
       [9.9961424e-01, 1.0075816e-05, 3.8067088e-07, ..., 1.9771530e-06,
        7.1091773e-07, 1.2927201e-06]], dtype=float32)

In [17]:
model.evaluate(X_test,y_test)

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 7.6026e-05 


[7.605167047586292e-05, 1.0]

In [18]:
y_classes = [
    "Left",  # 0
    "Right",       # 1
    "Volume down",            # 2
    "Volume up",           # 3
    "pause"            
]

In [19]:
sample = X_test[500].reshape(1, -1)
prediction = model.predict(sample)
predicted_class = np.argmax(prediction)
print("predicted_class:",y_classes[predicted_class])
print("actual_class:",y_classes[y_test[500]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
predicted_class: pause
actual_class: pause


In [ ]:
model.save("main_model.keras")